# -*- coding: utf-8 -*-
"""MAFFT + IQ-TREE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pNku-aqQw6bqnMRJd6_jIpbKlrUqz89F
"""

# Установка MAFFT в Google Colab
!apt-get update
!apt-get install -y mafft

# Запуск MAFFT на файле aligned_file.fasta
!mafft --auto combined_file.fasta > output_aligned.fasta

# Просмотр содержимого файла output_aligned.fasta в Google Colab
with open('/content/output_aligned.fasta', 'r') as file:
    print(file.read())

# Установка IQ-TREE
!apt-get update
!apt-get install -y iqtree

"""подаю файл output_aligned.fasta в iqtree2"""

!iqtree2 -s /content/output_aligned.fasta -m MFP -bb 1000 -alrt 1000 -nt AUTO -pre /content/output_tree

"""получила output_tree.treefile, output_tree.iqtree"""

with open('/content/output_tree.iqtree', 'r') as file:
    print(file.read())

with open('/content/output_tree.treefile', 'r') as file:
    print(file.read())